### ISSUE TITLE
duplicate class identifier

### ISSUE THREAD

**Issue by paztis** [whxaxes/js2dts#8]
Hi

When I generate dts from this js file:
```
export default class Test {
}
```

this is the result
```
// Generate by [js2dts](https://github.com/whxaxes/js2dts#readme)

declare class Test {
}
declare const Test: Test;
export default Test;
```

in this case the lib is redeclaring the `Test` variable for nothing (the class is already a variable)
It generates the exception `TS2300: duplicate class identifier`

Can you look at it ?

Thanks

**Comment by whxaxes** [comment]
It seems has some problem with esModule. I will fix it later today.

**Comment by whxaxes** [comment]
Hi, I just published a new version, upgrade `js2dts` to latest version and try again.

**Comment by paztis** [comment]
Thanks. Will try it today.
