### ISSUE TITLE
misenderstanding of the export .. from

### ISSUE THREAD

**Issue by paztis** [whxaxes/js2dts#9]
The generated dst from this file:
```
export {default} from './moduleA';
```

is:
```
// Generate by [js2dts](https://github.com/whxaxes/js2dts#readme)

declare const default: any;
export default default;
```

`default` cannot be used as a variable name
It results a TS error `TS1134: Variable declaration expected`

**Comment by whxaxes** [comment]
Upgrade to latest version and retry
